name: WolfyUtilities
api-version: 1.13
version: 0.1.4.0
author: WolfyScript
softdepend:
  - LWC
  - PlotSquared
  - WorldGuard

main: me.wolfyscript.utilities.main.Main

commands:
  wolfyutils:
    description: displays version of this plugin